name: Check quality of code
on:
  push:
    paths-ignore:
      - '.github/workflows/*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint:check

      - name: Format
        run: npm run format:check

      - name: Unit test
        run: npm run test:ci

      - name: E2E test
        run: npm run e2e:ci

      - name: Storybook
        run: npm run build-storybook

      - name: Build
        run: npm run build
